AWSTemplateFormatVersion: '2010-09-09'
Description: Grupo de seguridad compartido para acceso HTTP

Resources:
  MinticSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso HTTP desde cualquier lugar
      VpcId:
        Fn::ImportValue: Mintic-VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MinticSecurityGroup

Outputs:
  SecurityGroupId:
    Value: !Ref MinticSecurityGroup
    Export:
      Name: Mintic-SecurityGroupId
