AWSTemplateFormatVersion: '2010-09-09'
Description: Security Group para instancias EC2 con acceso HTTP, HTTPS y SSH

Resources:
  MinticSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para instancias EC2 con HTTP, HTTPS y SSH
      VpcId:
        Fn::ImportValue: Mintic-VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Permitir HTTP desde Internet
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: Permitir HTTPS desde Internet
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Permitir SSH desde Internet
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Permitir todo el trafico de salida
      Tags:
        - Key: Name
          Value: MinticSecurityGroup

Outputs:
  SecurityGroupId:
    Description: ID del Security Group
    Value: !Ref MinticSecurityGroup
    Export:
      Name: Mintic-SecurityGroupId